Feature/lvpytcdxii 19
lv-412-python/groups-service-repo pull request #1
Opened 2019-06-22 11:21 UTC by ement06

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=1032)

## Code reviewers

- [ ] @sikyrynskiy
- [ ] @olya_petryshyn
- [ ] @taraskonchak
- [ ] @OlyaKh00
- [ ] @ement06
- [ ] @iPavliv
- [ ] @khadai
- [ ] @Anastasia_Siromska
- [ ] @romichh

### Second Level Review

- [ ] @lhalam

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2019-07-02 12:02 UTC, iPavliv commented on groups_service/models/group.py
> +    id = Column(Integer(), primary_key=True) # pylint: disable=redefined-builtin, redefined-builtin, invalid-name
change to group_id and delete pylint disable comment

2019-07-02 14:32 UTC, LSikyr requested changes

2019-07-02 14:32 UTC, LSikyr commented on .gitignore
> +.vscode
No empty line in the end of the file. Very disappointed in you!!!

2019-07-02 14:32 UTC, LSikyr commented on Makefile
> +	pylint setup.py form_service/
Change form_service to group_service!!!!!!

2019-07-02 14:32 UTC, LSikyr commented on groups_service/migrations/README
> +Generic single-database configuration.
No blank line!!!!!!!!!!!!

2019-07-02 14:32 UTC, LSikyr commented on groups_service/models/group.py
> +from groups_service.db import DB
imports are not in alpabetic order

2019-07-02 14:32 UTC, LSikyr commented on groups_service/views/groups.py
> +    return jsonify({'message': 'Not correct URL'})
No need to jsonify dict!!!!

2019-07-02 14:32 UTC, LSikyr commented on groups_service/views/groups.py
> +    return jsonify({'message': 'Not correct URL'}), 400
multiple returns!!!!

2019-07-02 14:32 UTC, LSikyr commented on groups_service/views/groups.py
> +    return jsonify({'message': 'Not correct URL'}), 400
No need to jsonify dict!!!!

2019-07-02 14:32 UTC, LSikyr commented on groups_service/views/groups.py
> +    return jsonify(result.data)
GROUPS_SCHEMA.dump(groups).data
return result

2019-07-02 14:32 UTC, LSikyr commented on groups_service/views/groups.py
> +    return GROUP_SCHEMA.jsonify(new_group), 201
multiple returns

2019-07-02 14:32 UTC, LSikyr commented on groups_service/__init__.py
>  """Init users service"""
Copy paste detected!!!

2019-07-02 17:59 UTC, LSikyr approved these changes

2019-07-03 07:51 UTC, olyapetryshyn approved these changes

2019-07-03 07:51 UTC, merged